site_name: mrpwei.github.io
site_url: https://mrpwei.github.io
repo_url: https://github.com/mrpwei/mrpwei.github.io
theme:
  name: material
  language: zh
  palette:
    primary: teal
  icon:
    edit: material/pencil
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
edit_uri: edit/main/docs/
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
      # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
