site_name: Peng.Wei
site_author: Peng Wei
site_description: 彭伟的个人网站
site_url: https://mrpwei.github.io
repo_url: https://github.com/mrpwei/mrpwei.github.io
repo_name: mrpwei.github.io
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/images/hammer.svg
  favicon: assets/images/hammer.svg
  icon:
    edit: material/pencil
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
edit_uri: edit/main/docs/
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
      # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags: # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
      tags_file: tags.md
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
